# Site settings
name: Muharriana
title: Muharriana | Web Developer
description: Experienced professional specializing in web development, proficient in front-end and back-end technologies including HTML, CSS, JavaScript, and various frameworks. Proven track record of creating responsive and intuitive web applications, managing RESTful APIs, integrating external systems, and designing and implementing database schemas
url: https://muharyns.github.io/
baseurl: ''
email: muharriana@gmail.com
cover: https://muharyns.github.io/img/og.png
logo: https://muharyns.github.io/img/emojis/technologist.png
resume: https://muharyns.github.io/resume-1.pdf
social:
  - title: email
    url: mailto:muharriana@gmail.com
  - title: github
    url: https://github.com/muharyns
  - title: linkedin
    url: https://www.linkedin.com/in/muharriana/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
